- name: Checking if oh-my-zsh is installed
  stat:
    path: "{{ home_directory }}/.oh-my-zsh"
  register: zsh_install_directory

- name: Downloading oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: ~/install-ohmyzsh.sh
    mode: +x
  when: zsh_install_directory.stat.exists == false
  register: install_ohmyzsh

- name: Installing oh-my-zsh
  command: ~/install-ohmyzsh.sh
  when: zsh_install_directory.stat.exists == false

- name: Fixing /usr/local/share/zsh permissions
  file:
    path: /usr/local/share/zsh
    mode: g-w
    recurse: yes

- name: Deleting oh-my-zsh install.sh
  file:
    path: ~/install-ohmyzsh.sh
    state: absent