---
- name: Installing supervisor
  homebrew:
    name: supervisor
  when: brew_packages.stdout is not search('supervisor')
  notify:
    - Restart supervisord

- name: Configuring supervisor
  template:
    src: supervisord.conf.j2
    dest: /usr/local/etc/supervisord.conf
  notify:
    - Restart supervisord

- name: Creating configuration directory
  file:
    path: /usr/local/share/supervisor/conf.d
    state: directory
